services:
  webhawk:
    build: .
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
  ollama:
    image: ollama/ollama
    command: serve
    ports:
      - "11434:11434"