version: '3.8'
services:
  webhawk:
    build:
      context: ./webhawk
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./webhawk:/app

  ollama:
    image: ollama/ollama
    command: serve
    ports:
      - "11434:11434"

  webhawk_app:
    build:
      context: ./webhawk_app
    working_dir: /app
    command: bash -c "bin/bundle install && bin/rails db:migrate && rm -f tmp/pids/server.pid && bin/bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./webhawk_app:/app
